# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Smattering of Stories
description: >
  An eclectic mixture of stories, ranging from
  a bedtime-crowd-sourced children’s detective series
  to assorted surreal-ish, near-future musings,
  and some other stuff,
  and some notes on using Jekyll (to create this site).
baseurl: "" # the subpath of your site, e.g. /blog
url: http://stories.upthebuzzard.com # upthebuzzard.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: upthebuzzard
github_username:  upthebuzzard
github_repo: https://github.com/upthebuzzard/upthebuzzard.github.io
author: Chris Gathercole
lang: en
default_background_image_url: /assets/img/general/P1070749-H800.JPG
auto-generated-title: "in the style of..."
google_analytics: UA-92309370-1

license_name: Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
license_url: http://creativecommons.org/licenses/by-nc-sa/3.0/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap # via https://help.github.com/articles/sitemaps-for-github-pages/
  - jekyll-redirect-from # via https://help.github.com/articles/redirects-on-github-pages/
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  moose_and_goose_stories:
    output: true
    title: The Moose and Goose Stories
    title_singular: A Moose and Goose Story
    description: a collection of stories about Moose and Goose, Solvers of Tricky Problems
    sequence: 1
    background_image_url: /assets/img/moose-and-goose/P1070818-H800.JPG
  grey_parrot_stories:
    output: true
    title: The Grey Parrot Stories
    title_singular: A Grey Parrot Story
    description: a collection of stories about the (too) clever grey parrot
    sequence: 2
    background_image_url: /assets/img/grey-parrot/P1070812-H800.JPG
  predicting_the_present:
    output: true
    title: Predicting the Present
    title_singular: A Predicting the Present Story
    description: these short stories are less predicting the future and more “predicting the present”.
    sequence: 10
  emus_all_the_way_down:
    output: true
    title: Emus All The Way Down
    title_singular: Emus All The Way Down
    description: riffing on the Predicting The Present story "Emus All The Way Down".
    sequence: 11
  fragments:
    output: true
    title: Fragments of writing
    title_singular: A Fragment
    description: riffing on whatever is riff-worthy
    sequence: 20
    reverse_posts: true
  games:
    output: true
    title: Notes on games
    title_singular: A Note
    description: exploring games
    sequence: 30
    reverse_posts: true
    background_image_url: /assets/img/greedy-devils/P1080042w800.JPG
  overgeneralisations:
    output: true
    title: Overgeneralisations
    title_singular: An Overgeneralisation
    description: observations based on insufficient evidence
    sequence: 40
    reverse_posts: true
  distractions:
    output: true
    title: Distractions
    title_singular: A Distraction
    description: a collection of interesting links
    sequence: 90
  jekyll_notes:
    output: true
    title: Jekyll Notes
    title_singular: A Jekyll Note
    description: a collection of notes and observations from and aide-memoires for using Jekyll for the first time.
    sequence: 100
    background_image_url: /assets/img/jekyll-notes/JekyllAndHydeWikipedia.jpg
    reverse_posts: true
